module.exports=async c=>{
 const path=require('path'),axePath=path.join(c.root,'reports/full-e2e-qa/tooling/node_modules/axe-core/axe.min.js');const findings=[],responsive=[];c.publicPages={};
 const audit=async(p,app,screen)=>{await p.addScriptTag({path:axePath});const a=await p.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return {violations:r.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,failureSummary:n.failureSummary}))})),incomplete:r.incomplete.map(v=>v.id)};});findings.push({app,screen,...a});c.save('logs/'+app+'-'+screen+'-public-continuation.json',{snapshot:await p.locator('body').ariaSnapshot()});await p.screenshot({path:c.report+'/screenshots/'+app+'-'+screen+'-public-continuation.png',fullPage:true});};
 for(const [app,port]of Object.entries({customer:8082,plumber:8083,store:8084,admin:3001})){const context=await c.browser.newContext(),p=await context.newPage();c.publicPages[app]=p;const dialogs=[];p.on('dialog',async d=>{dialogs.push(d.message());await d.dismiss()});await p.goto('http://localhost:'+port,{waitUntil:'domcontentloaded'});await p.waitForTimeout(2000);await audit(p,app,'login');
 const focus=[];for(let i=0;i<8;i++){await p.keyboard.press('Tab');focus.push(await p.evaluate(()=>({tag:document.activeElement.tagName,role:document.activeElement.getAttribute('role'),name:document.activeElement.getAttribute('aria-label')||document.activeElement.textContent?.slice(0,70)})));}c.save('logs/'+app+'-keyboard-continuation.json',focus);
 for(const [width,height]of [[360,800],[390,844],[412,915],[768,1024],[1024,768],[1366,768],[1440,900],[1920,1080]]){await p.setViewportSize({width,height});const metrics=await p.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth,scrollHeight:document.documentElement.scrollHeight}));responsive.push({app,screen:'public login',width,height,...metrics,result:metrics.scrollWidth<=width?'PASS':'FAIL',scope:'horizontal overflow only; screenshot saved for review'});await p.screenshot({path:c.report+`/screenshots/${app}-public-${width}x${height}-continuation.png`,fullPage:true});}
 await p.setViewportSize({width:390,height:844});
 if(app==='plumber'){await p.getByRole('button',{name:'Continue',exact:true}).click();await audit(p,app,'empty-validation');await p.getByRole('button',{name:'Forgot password'}).click();await audit(p,app,'forgot');await p.getByText('New here? Sign up',{exact:true}).click();await audit(p,app,'registration');}
 if(app==='store'){await p.getByRole('button',{name:'Log In',exact:true}).click();await audit(p,app,'empty-validation');await p.getByText('Forgot Password?',{exact:true}).click();await audit(p,app,'forgot');await p.getByText('Register Store',{exact:true}).click();await audit(p,app,'registration');}
 if(app==='customer'){await p.getByRole('textbox',{name:'Mobile number input'}).fill('123');c.record('CUSTOMER-SHORT-PHONE','Customer','Short phone disables OTP submission',await p.getByRole('button',{name:'Get OTP button'}).isDisabled()?'PASS':'FAIL','Three digit input');await audit(p,app,'invalid-phone');}
 c.save('logs/'+app+'-public-dialogs-continuation.json',dialogs);
 c.save('logs/accessibility-continuation.json',findings);c.save('logs/responsive-continuation.json',responsive);
 }
 for(const app of ['plumber','store','admin']){const p=c.pages[app];for(const [width,height]of [[360,800],[390,844],[412,915],[768,1024],[1024,768],[1366,768],[1440,900],[1920,1080]]){await p.setViewportSize({width,height});const metrics=await p.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth}));responsive.push({app,screen:'authenticated current screen',width,height,...metrics,result:metrics.scrollWidth<=width?'PASS':'FAIL',scope:'horizontal overflow only; screenshot saved for review'});await p.screenshot({path:c.report+`/screenshots/${app}-authenticated-${width}x${height}-continuation.png`,fullPage:true});}await p.setViewportSize({width:1366,height:768});await audit(p,app,'authenticated');}
 c.save('logs/accessibility-continuation.json',findings);c.save('logs/responsive-continuation.json',responsive);c.flush();
};
