module.exports=async c=>{
 const health=[];for(let i=0;i<12;i++){const r=await c.api('GET','/health/ready');health.push(r);if(r.status===200)break;await new Promise(r=>setTimeout(r,3000));}c.save('logs/backend-ready-poll-continuation.json',health);
 const endpoints=[];for(const url of ['/health/live','/health/ready','/version','/actuator/health','/actuator/info'])endpoints.push({url,...await c.api('GET',url)});c.save('logs/backend-health-ready-continuation.json',endpoints);
 c.save('logs/backend-isolated-ready-qa.log',c.docker(['logs','fixkart_retest_backend_20260914']).split('\n').filter(x=>!/password|authorization|refreshToken|secret/i.test(x)).join('\n'));
 const identities={CUSTOMER:'customer.qa@fixkart.com',CUSTOMER2:'customer2.qa@fixkart.com',PLUMBER:'plumber.qa@fixkart.com',PLUMBER2:'plumber2.qa@fixkart.com',STORE_MANAGER:'store.qa@fixkart.com',SUPER_ADMIN:'superadmin@plumbcommerce.com',OPERATIONS_ADMIN:'operations@plumbcommerce.com',FINANCE_ADMIN:'finance@plumbcommerce.com',SUPPORT_ADMIN:'support@plumbcommerce.com',PLUMBER_MANAGER:'plumbermanager@plumbcommerce.com',MARKETING_ADMIN:'marketing@plumbcommerce.com'};c.identities=identities;
 const auth=[];for(const [role,email]of Object.entries(identities)){const r=await c.api('POST','/api/v1/auth/login',null,{email,password:c.password});const d=r.data||{};if(d.token||d.accessToken){c.tokens[role]=d.token||d.accessToken;c.users[role]=d;c.refresh=c.refresh||{};c.refresh[role]=d.refreshToken;}auth.push({role,status:r.status,returnedRole:d.role,userId:d.userId,accessTokenPresent:!!c.tokens[role],refreshTokenPresent:!!d.refreshToken,ms:r.ms});c.record('AUTH-'+role,'Backend',role+' real password login',r.status===200&&!!c.tokens[role]?'PASS':'FAIL','HTTP '+r.status);if(c.tokens[role]){const me=await c.api('GET','/api/v1/auth/me',role);auth.push({role,endpoint:'/api/v1/auth/me',status:me.status,userId:me.data?.id,returnedRole:me.data?.role});}}
 c.save('logs/auth-continuation.json',auth);
 for(const [app,role]of Object.entries({plumber:'PLUMBER',store:'STORE_MANAGER',admin:'SUPER_ADMIN'})){const p=c.pages[app];try{if(app==='plumber')await p.getByRole('tab',{name:'Log in with email'}).click();const inputs=p.locator('input');await inputs.nth(0).fill(identities[role]);await inputs.nth(1).fill(c.password);await p.getByRole('button',{name:app==='admin'?'Sign in':app==='store'?'Log In':'Continue',exact:true}).click();await p.waitForTimeout(2500);c.save('logs/'+app+'-login-continuation.json',{url:p.url(),snapshot:await p.locator('body').ariaSnapshot(),text:await p.locator('body').innerText()});await p.screenshot({path:c.report+'/screenshots/'+app+'-login-continuation.png',fullPage:true});}catch(e){c.save('logs/'+app+'-login-error-continuation.log',e.message);}}
 const p=c.pages.customer;await p.getByRole('textbox',{name:'Mobile number input'}).fill('5555500001');await p.getByRole('button',{name:'Get OTP button'}).click();await p.waitForTimeout(3000);c.save('logs/customer-otp-request-continuation.json',{snapshot:await p.locator('body').ariaSnapshot(),text:await p.locator('body').innerText()});c.flush();
};
