CREATE TABLE IF NOT EXISTS settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beneficiary_type VARCHAR(50) NOT NULL,
    beneficiary_id BIGINT NOT NULL,
    gross_amount DECIMAL(19, 2) NOT NULL DEFAULT 0,
    commission_amount DECIMAL(19, 2) NOT NULL DEFAULT 0,
    net_amount DECIMAL(19, 2) NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP,
    paid_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refund_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    amount DECIMAL(19, 2) NOT NULL DEFAULT 0,
    reason TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    finance_note TEXT,
    requested_at TIMESTAMP,
    processed_at TIMESTAMP
);