CREATE TABLE plumber_kyc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plumber_id BIGINT NOT NULL UNIQUE,
    aadhaar_number_masked VARCHAR(64), pan_number_masked VARCHAR(64), experience_years INTEGER,
    service_areas VARCHAR(1000), bank_account_masked VARCHAR(64), document_status VARCHAR(64),
    status VARCHAR(32) NOT NULL, availability_status VARCHAR(32) NOT NULL,
    availability_reason VARCHAR(1000), submitted_at TIMESTAMP, reviewed_at TIMESTAMP,
    reviewed_by_admin_id BIGINT, rejection_reason VARCHAR(1000),
    CONSTRAINT fk_plumber_kyc_user FOREIGN KEY (plumber_id) REFERENCES users(id)
);
CREATE INDEX idx_plumber_kyc_status ON plumber_kyc(status);
CREATE INDEX idx_plumber_availability ON plumber_kyc(availability_status);
