services:
  - type: web
    name: plumbcommerce-backend
    runtime: docker
    rootDir: backend
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod,staging
      - key: APP_SCHEDULING_ENABLED
        value: false
      - key: APP_DEMO_SEED_ENABLED
        value: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_SSL
        value: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: SMS_PROVIDER
        value: disabled
      - key: MONGO_URI
        sync: false
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_USERNAME
        sync: false
      - key: KAFKA_PASSWORD
        sync: false
      - key: KAFKA_SECURITY_PROTOCOL
        sync: false
      - key: KAFKA_SASL_MECHANISM
        sync: false
