export const typography = {
  fontFamily: {
    heading: 'Manrope',
    body: 'Inter',
    label: 'Inter',
    regular: 'Inter',
    medium: 'Inter',
    bold: 'Inter',
    black: 'Inter',
  },
  fontSize: {
    labelSm: 10,
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    heading: 32,
  },
  lineHeight: {
    labelSm: 14,
    tight: 16,
    normal: 20,
    relaxed: 24,
    headingMd: 28,
    headingLg: 32,
    headingXl: 40,
  },
  fontWeight: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
    black: '900' as const,
  },
  styles: {
    headlineXl: {
      fontFamily: 'Manrope',
      fontSize: 32,
      fontWeight: '700' as const,
      lineHeight: 40,
    },
    headlineLg: {
      fontFamily: 'Manrope',
      fontSize: 24,
      fontWeight: '700' as const,
      lineHeight: 32,
    },
    headlineMd: {
      fontFamily: 'Manrope',
      fontSize: 20,
      fontWeight: '600' as const,
      lineHeight: 28,
    },
    headlineSm: {
      fontFamily: 'Manrope',
      fontSize: 18,
      fontWeight: '600' as const,
      lineHeight: 24,
    },
    bodyLg: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '400' as const,
      lineHeight: 24,
    },
    bodyMd: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    bodySm: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 16,
    },
    labelLg: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '600' as const,
      lineHeight: 20,
    },
    labelMd: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '500' as const,
      lineHeight: 16,
    },
    labelSm: {
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: '500' as const,
      lineHeight: 14,
    },
  },
};

