/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import StatCard from "@/components/admin-shell/StatCard";
import StatusBadge from "@/components/admin-shell/StatusBadge";
import { getSupportDashboard, listSupportTickets, type SupportDashboardResponse, type SupportTicketSummary } from "@/services/supportService";
import { formatDate, supportTone } from "./supportHelpers";

export default function SupportDashboardPage() { const [dashboard,setDashboard]=useState<SupportDashboardResponse|null>(null); const [recent,setRecent]=useState<SupportTicketSummary[]>([]); const [urgent,setUrgent]=useState<SupportTicketSummary[]>([]); const [escalated,setEscalated]=useState<SupportTicketSummary[]>([]); const [error,setError]=useState(""); const load=useCallback(async()=>{setError(""); try{const [d,r,u,e]=await Promise.all([getSupportDashboard(),listSupportTickets({size:5}),listSupportTickets({priority:"URGENT",size:5}),listSupportTickets({status:"ESCALATED",size:5})]); setDashboard(d); setRecent(r.content); setUrgent(u.content); setEscalated(e.content);}catch(x){setError(x instanceof Error?x.message:"Unable to load support dashboard");}},[]); useEffect(()=>{void load();},[load]); const cards=[["Open Tickets",dashboard?.openTickets??0],["In Progress",dashboard?.inProgressTickets??0],["Escalated",dashboard?.escalatedTickets??0],["Resolved Today",dashboard?.resolvedToday??0],["Urgent Tickets",dashboard?.urgentTickets??0],["Payment Issues",dashboard?.paymentIssues??0],["Delivery Issues",dashboard?.deliveryIssues??0],["Service Issues",dashboard?.serviceIssues??0]] as const; const list=(title:string,href:string,rows:SupportTicketSummary[])=><section className="panel"><div className="panel-header"><h2 className="panel-title">{title}</h2><Link className="inline-link" href={href}>View</Link></div><div className="stack">{rows.map(t=><div className="live-job-card" key={t.ticketId}><div><div className="row-title">{t.ticketNumber} - {t.subject}</div><div className="row-subtitle">{t.requesterName} - {t.category} - {formatDate(t.updatedAt)}</div></div><StatusBadge tone={supportTone(t.status)}>{t.status}</StatusBadge></div>)}</div></section>; return <div className="stack"><section className="panel"><div className="page-header"><div><h1 className="page-title">Support Dashboard</h1><p className="page-subtitle">Ticket queue, escalations, complaints, and customer issue workflow.</p></div><button className="button button-secondary" type="button" onClick={()=>void load()}>Refresh</button></div>{error?<div className="field-error">{error}</div>:null}<div className="stat-grid">{cards.map(([label,value],i)=><StatCard key={label} label={label} value={value} accent={["#2563eb","#f59e0b","#ef4444","#10b981","#8b5cf6"][i%5]}/>)}</div></section><div className="two-col">{list("Recent Tickets","/support/tickets",recent)}{list("Urgent Tickets","/support/tickets",urgent)}</div>{list("Escalated Tickets","/support/escalations",escalated)}</div>; }