import { apiRequest } from "./apiClient";

export type SupportStatus = "OPEN" | "IN_PROGRESS" | "ESCALATED" | "RESOLVED" | "CLOSED";
export type SupportPriority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";
export type SupportCategory = "PRODUCT_ORDER" | "SERVICE_JOB" | "PAYMENT" | "REFUND" | "DELIVERY" | "PLUMBER_SERVICE" | "STORE_ISSUE" | "ACCOUNT" | "OTHER";
export type SupportRole = "SUPER_ADMIN" | "ADMIN" | "OPERATIONS_ADMIN" | "PLUMBER_MANAGER" | "FINANCE_ADMIN" | "SUPPORT_ADMIN" | "MARKETING_ADMIN" | "STORE_MANAGER" | "CUSTOMER" | "PLUMBER" | "DELIVERY_PARTNER";
export interface PageResponse<T> { content: T[]; number: number; size: number; totalElements: number; totalPages: number; }
export interface SupportTicketSummary { ticketId: number; ticketNumber: string; requesterName: string; requesterRole: SupportRole; subject: string; category: SupportCategory; priority: SupportPriority; status: SupportStatus; assignedAdminName?: string | null; relatedProductOrderId?: number | null; relatedServiceOrderId?: number | null; escalationReason?: string | null; createdAt?: string | null; updatedAt?: string | null; }
export interface SupportDashboardResponse { openTickets: number; inProgressTickets: number; escalatedTickets: number; resolvedToday: number; urgentTickets: number; paymentIssues: number; deliveryIssues: number; serviceIssues: number; averageResolutionHours?: number | null; recentTickets: SupportTicketSummary[]; urgentTicketList: SupportTicketSummary[]; escalatedTicketList: SupportTicketSummary[]; }
export interface SupportMessageResponse { messageId: number; ticketId: number; senderId?: number | null; senderName?: string | null; senderRole: SupportRole; message: string; internalNote: boolean; createdAt?: string | null; }
export interface SupportTicketDetail extends SupportTicketSummary { requesterId: number; requesterEmail?: string | null; requesterPhone?: string | null; productOrderStatus?: string | null; serviceOrderStatus?: string | null; description: string; assignedAdminId?: number | null; messages: SupportMessageResponse[]; resolvedAt?: string | null; }
export interface SupportUserContextResponse { userId: number; fullName: string; email: string; phone: string; role: SupportRole; recentProductOrders: { orderId: number; totalAmount: number; status: string; createdAt?: string | null }[]; recentServiceJobs: { jobId: number; totalAmount: number; status: string; description?: string | null; createdAt?: string | null }[]; previousTickets: SupportTicketSummary[]; }
export interface SupportTicketCreateRequest { requesterId: number; requesterRole: SupportRole; relatedProductOrderId?: number | null; relatedServiceOrderId?: number | null; category: SupportCategory; priority: SupportPriority; subject: string; description: string; }
function qs(params: Record<string, string | number | undefined>) { const q = new URLSearchParams(); Object.entries(params).forEach(([k,v]) => { if (v !== undefined && v !== "") q.set(k, String(v)); }); const s = q.toString(); return s ? `?${s}` : ""; }
export const getSupportDashboard = () => apiRequest<SupportDashboardResponse>("/api/v1/admin/support/dashboard");
export const listSupportTickets = (query: { status?: string; priority?: string; category?: string; requesterRole?: string; search?: string; page?: number; size?: number } = {}) => apiRequest<PageResponse<SupportTicketSummary>>(`/api/v1/admin/support/tickets${qs({ ...query, page: query.page ?? 0, size: query.size ?? 10 })}`);
export const getSupportTicket = (id: string | number) => apiRequest<SupportTicketDetail>(`/api/v1/admin/support/tickets/${id}`);
export const createSupportTicket = (body: SupportTicketCreateRequest) => apiRequest<SupportTicketDetail>("/api/v1/admin/support/tickets", { method: "POST", body });
export const addSupportMessage = (id: string | number, message: string, internalNote: boolean) => apiRequest<SupportMessageResponse>(`/api/v1/admin/support/tickets/${id}/messages`, { method: "POST", body: { message, internalNote } });
export const assignSupportTicket = (id: string | number, adminUserId: number) => apiRequest<SupportTicketSummary>(`/api/v1/admin/support/tickets/${id}/assign`, { method: "PATCH", body: { adminUserId } });
export const updateSupportTicketStatus = (id: string | number, status: SupportStatus) => apiRequest<SupportTicketSummary>(`/api/v1/admin/support/tickets/${id}/status`, { method: "PATCH", body: { status } });
export const escalateSupportTicket = (id: string | number, reason: string) => apiRequest<SupportTicketSummary>(`/api/v1/admin/support/tickets/${id}/escalate`, { method: "PATCH", body: { reason } });
export const closeSupportTicket = (id: string | number, resolutionNote: string) => apiRequest<SupportTicketSummary>(`/api/v1/admin/support/tickets/${id}/close`, { method: "PATCH", body: { resolutionNote } });
export const getSupportUserContext = (userId: string | number) => apiRequest<SupportUserContextResponse>(`/api/v1/admin/support/context/user/${userId}`);