const fs=require('fs'),path=require('path'),{request}=require('playwright');const root=__dirname,run=new Date().toISOString().replace(/[:.]/g,'-'),out=path.join(root,run);fs.mkdirSync(out,{recursive:true});const base='https://plumbing-qcommerce.onrender.com';const legacy=fs.readFileSync(path.join(root,'../../run-development2-live-e2e.js'),'utf8');const secret=process.env.APP_SEED_DEMO_PASSWORD||legacy.match(/const QA_PASSWORD = process\.env\.APP_SEED_DEMO_PASSWORD \|\| '([^']+)'/)[1];
const results=[];function clean(k,v){if(/password|token|secret|authorization|cookie/i.test(k))return '[REDACTED]';return typeof v==='string'?v.replaceAll(secret,'[REDACTED]').replace(/eyJ[\w-]+\.[\w-]+\.[\w-]+/g,'[REDACTED JWT]'):v}function save(){fs.writeFileSync(path.join(out,'api-results.json'),JSON.stringify(results,clean,2))}
(async()=>{const http=await request.newContext({timeout:45000});async function req(label,method,url,options={}){const t=Date.now();try{const r=await http.fetch(base+url,{method,...options});let body;try{body=await r.json()}catch{body=(await r.text()).slice(0,1500)}const x={label,time:new Date().toISOString(),method,url,status:r.status(),ms:Date.now()-t,headers:r.headers(),body};results.push(x);save();console.log(JSON.stringify(x,clean));return body}catch(e){results.push({label,url,error:e.message,ms:Date.now()-t});save();return null}}
for(const origin of ['https://fixkart-customer-web.vercel.app','https://fixkart-plumber-web.vercel.app','https://fixkart-store-web.vercel.app','https://admin-portal-ten-weld.vercel.app','https://qa-untrusted.invalid'])await req('CORS '+origin,'OPTIONS','/api/v1/auth/login',{headers:{Origin:origin,'Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'content-type'}});
await req('Missing credentials','GET','/api/v1/auth/me');await req('Malformed bearer','GET','/api/v1/auth/me',{headers:{Authorization:'Bearer invalid'}});
await req('Public categories','GET','/api/v1/catalog/categories');await req('Public products','GET','/api/v1/catalog/products');
for(const q of ["' OR '1'='1",'<script>alert(1)</script>','${7*7}','../','工具🔧','x'.repeat(400)])await req('Search validation '+q.slice(0,40),'GET','/api/v1/catalog/search?q='+encodeURIComponent(q));
await req('Empty login','POST','/api/v1/auth/login',{data:{email:'',password:''}});
for(const actor of ['customer','plumber','store','admin']){
const d=await req(actor+' configured QA login','POST','/api/v1/auth/login',{data:{email:actor+'.qa@fixkart.com',password:secret}});
const token=d?.accessToken||d?.token||d?.data?.accessToken;if(token){await req(actor+' authenticated identity','GET','/api/v1/auth/me',{headers:{Authorization:'Bearer '+token}})}
}
await http.dispose();console.log('EVIDENCE',out)})().catch(e=>{console.error(e.message);process.exitCode=1});
