const fs=require('fs'),path=require('path'),{chromium}=require('playwright');
const root=__dirname,run=new Date().toISOString().replace(/[:.]/g,'-'),out=path.join(root,run);fs.mkdirSync(out,{recursive:true});
const legacy=fs.readFileSync(path.join(root,'../../run-development2-live-e2e.js'),'utf8');const secret=process.env.APP_SEED_DEMO_PASSWORD||legacy.match(/const QA_PASSWORD = process\.env\.APP_SEED_DEMO_PASSWORD \|\| '([^']+)'/)[1];
function safe(k,v){if(/password|token|secret|authorization|cookie/i.test(k))return '[REDACTED]';return typeof v==='string'?v.replaceAll(secret,'[REDACTED]').replace(/eyJ[\w-]+\.[\w-]+\.[\w-]+/g,'[REDACTED JWT]'):v}function save(n,d){fs.writeFileSync(path.join(out,n),JSON.stringify(d,safe,2))}
const urls={customer:'https://fixkart-customer-web.vercel.app',plumber:'https://fixkart-plumber-web.vercel.app',store:'https://fixkart-store-web.vercel.app',admin:'https://admin-portal-ten-weld.vercel.app'};
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const [actor,url]of Object.entries(urls)){
const c=await b.newContext({viewport:{width:1440,height:900}}),p=await c.newPage(),events=[];const dir=path.join(root,'screenshots',actor,run);fs.mkdirSync(dir,{recursive:true});
p.on('console',m=>{if(['warning','error'].includes(m.type()))events.push({type:m.type(),text:m.text()})});p.on('pageerror',e=>events.push({type:'pageerror',text:e.message}));p.on('dialog',async d=>{events.push({type:'dialog',text:d.message()});await d.dismiss()});p.on('requestfailed',r=>events.push({type:'requestfailed',url:r.url(),error:r.failure()?.errorText}));const pending=[];p.on('response',r=>{pending.push((async()=>{const x={type:'response',url:r.url(),status:r.status(),method:r.request().method(),timing:r.request().timing()};if(/\/api\//.test(r.url()))try{x.body=await r.json()}catch{}events.push(x)})())});
try{await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});if(actor==='customer'){await p.getByRole('button',{name:'Skip onboarding'}).waitFor({timeout:30000});await p.getByRole('button',{name:'Skip onboarding'}).click();}if(actor==='plumber'){await p.getByText('Email',{exact:true}).waitFor({timeout:30000});await p.getByText('Email',{exact:true}).click()}
await p.locator('input[type=email]').waitFor({timeout:30000});const btn=p.getByRole('button',{name:actor==='customer'?'Login':actor==='plumber'?'Continue':actor==='store'?'Log In':'Sign in',exact:true});
await btn.click();await p.screenshot({path:path.join(dir,'empty-submit.png'),fullPage:true});save(actor+'-empty.json',{text:await p.locator('body').innerText(),events});
await p.locator('input[type=email]').fill(actor+'.qa@fixkart.com');await p.locator('input[type=password]').fill(secret);
const start=Date.now();const requestPromise=p.waitForResponse(r=>/\/auth\/(login|authenticate)/.test(r.url()),{timeout:45000}).catch(e=>({error:e.message}));await btn.click();const r=await requestPromise;let response;if(r.status){let body;try{body=await r.json()}catch{body=await r.text()}response={url:r.url(),status:r.status(),body,ms:Date.now()-start}}else response=r;
await p.waitForLoadState('networkidle',{timeout:30000}).catch(()=>{});await p.screenshot({path:path.join(dir,'login-result.png'),fullPage:true,mask:[p.locator('input[type=password]')]});await Promise.allSettled(pending);save(actor+'-login.json',{url:p.url(),response,text:await p.locator('body').innerText(),events});console.log(actor,JSON.stringify({response,text:await p.locator('body').innerText()},safe));
}catch(e){save(actor+'-error.json',{error:e.message,events});console.log(actor,e.message)}finally{await Promise.allSettled(pending);save(actor+'-events.json',events);await c.close()}
}}finally{await b.close()}console.log('EVIDENCE',out)})().catch(e=>{console.error(e.message);process.exitCode=1});
