const fs=require('fs'),path=require('path'),{chromium}=require('playwright'),axe=require('./tooling/node_modules/axe-core');
const root=__dirname,run=new Date().toISOString().replace(/[:.]/g,'-'),out=path.join(root,run);fs.mkdirSync(out,{recursive:true});
const urls={customer:'https://fixkart-customer-web.vercel.app',plumber:'https://fixkart-plumber-web.vercel.app',store:'https://fixkart-store-web.vercel.app',admin:'https://admin-portal-ten-weld.vercel.app'};
const viewports=[[360,800],[390,844],[412,915],[768,1024],[1024,768],[1366,768],[1440,900],[1920,1080]];
function save(n,d){fs.writeFileSync(path.join(out,n),JSON.stringify(d,(k,v)=>/password|token|secret|authorization|cookie/i.test(k)?'[REDACTED]':v,2))}
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const [actor,url]of Object.entries(urls).filter(([a])=>!process.env.QA_ACTORS||process.env.QA_ACTORS.split(',').includes(a))){
 const c=await b.newContext({viewport:{width:1440,height:900}}),p=await c.newPage(),events=[],actions=[];let seq=0;
 p.on('dialog',async d=>{events.push({type:'dialog',text:d.message()});await d.dismiss()});p.on('console',m=>{if(['warning','error'].includes(m.type()))events.push({type:m.type(),text:m.text()})});p.on('pageerror',e=>events.push({type:'pageerror',text:e.message}));p.on('request',r=>{if(/\/api\//.test(r.url()))events.push({type:'request',url:r.url(),method:r.method()})});p.on('response',r=>{if(/\/api\//.test(r.url())||r.status()>=400)events.push({type:'response',url:r.url(),status:r.status()})});p.on('requestfailed',r=>events.push({type:'requestfailed',url:r.url(),error:r.failure()?.errorText}));
 const shots=path.join(root,'screenshots',actor,run);fs.mkdirSync(shots,{recursive:true});
 async function settled(){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{})}
 async function snap(label){await settled();const n=String(++seq).padStart(2,'0')+'-'+label;await p.screenshot({path:path.join(shots,n+'.png'),fullPage:true,mask:[p.locator('input[type=password]')]});const d={url:p.url(),text:await p.locator('body').innerText(),aria:await p.locator('body').ariaSnapshot(),inputs:await p.locator('input').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width).map(e=>({type:e.type,placeholder:e.placeholder,label:e.getAttribute('aria-label'),labels:[...e.labels||[]].map(l=>l.innerText),required:e.required,maxLength:e.maxLength,validity:e.validity.valid}))),controls:await p.locator('button,a,input,select,textarea,[tabindex="0"],[role=tab],[role=checkbox]').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height).map(e=>({tag:e.tagName,role:e.getAttribute('role'),text:(e.innerText||'').trim().slice(0,150),label:e.getAttribute('aria-label'),placeholder:e.getAttribute('placeholder'),type:e.type}))),events:[...events]};save(actor+'-'+n+'.json',d);return d}
 async function action(label,fn){const start=events.length,before=await p.locator('body').innerText();try{await fn();await settled();const after=await p.locator('body').innerText();actions.push({label,time:new Date().toISOString(),before,after,events:events.slice(start),executed:true});console.log(actor,label,JSON.stringify({changed:before!==after,events:events.slice(start)}));}catch(e){actions.push({label,executed:false,error:e.message});console.log(actor,label,e.message.slice(0,180))}save(actor+'-actions.json',actions)}
 const click=t=>p.getByText(t,{exact:true}).filter({visible:true}).last().click({timeout:7000});
 async function measure(screen){await p.addScriptTag({content:axe.source});const a=await p.evaluate(async()=>await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));save(actor+'-'+screen+'-axe.json',{version:a.testEngine.version,url:a.url,violations:a.violations,incomplete:a.incomplete,passes:a.passes.map(x=>x.id)});
 const sizes=[];for(const[width,height]of viewports){await p.setViewportSize({width,height});await settled();const metrics=await p.evaluate(()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth,overflow:[...document.querySelectorAll('input,button,[tabindex="0"]')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&(r.left<0||r.right>innerWidth+1)}).map(e=>({text:e.innerText,placeholder:e.getAttribute('placeholder'),rect:{x:e.getBoundingClientRect().x,width:e.getBoundingClientRect().width}}))}));sizes.push(metrics);const dir=path.join(root,'screenshots','responsive',run);fs.mkdirSync(dir,{recursive:true});await p.screenshot({path:path.join(dir,actor+'-'+screen+'-'+width+'x'+height+'.png'),fullPage:true,mask:[p.locator('input[type=password]')]})}save(actor+'-'+screen+'-responsive.json',sizes);await p.setViewportSize({width:1440,height:900});
 const keys=[];for(let i=0;i<14;i++){await p.keyboard.press(i===13?'Shift+Tab':'Tab');keys.push(await p.evaluate(()=>({tag:document.activeElement.tagName,role:document.activeElement.getAttribute('role'),label:document.activeElement.getAttribute('aria-label'),text:document.activeElement.innerText?.slice(0,70),placeholder:document.activeElement.getAttribute('placeholder'),outline:getComputedStyle(document.activeElement).outline})));}save(actor+'-'+screen+'-keyboard.json',keys);await p.emulateMedia({reducedMotion:'reduce'});save(actor+'-'+screen+'-reduced-motion.json',await p.evaluate(()=>({matches:matchMedia('(prefers-reduced-motion: reduce)').matches,activeAnimations:document.getAnimations().map(a=>({playState:a.playState,timing:a.effect.getComputedTiming()}))})));await p.emulateMedia({reducedMotion:'no-preference'});
 }
 try{await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});if(actor==='customer'){await p.getByRole('button',{name:'Skip onboarding'}).waitFor({timeout:30000});await action('Skip onboarding',()=>p.getByRole('button',{name:'Skip onboarding'}).click())}else await p.locator('input').first().waitFor({timeout:30000});
 if(actor==='plumber'){
 await action('Mobile empty continue',async()=>{await p.locator('input:visible').fill('');await click('Continue')});await snap('mobile-empty');if(await p.getByText('Verify Your Number',{exact:true}).isVisible().catch(()=>false)){await measure('otp');await action('OTP back',()=>click('←'));}await action('Mobile letters',()=>p.locator('input:visible').fill('abc<>'));await snap('mobile-letters');await action('Mobile too short',async()=>{await p.locator('input:visible').fill('123');await click('Continue')});await snap('mobile-short');if(await p.getByText('Verify Your Number',{exact:true}).isVisible().catch(()=>false))await action('OTP back',()=>click('←'));await action('Remember me on',()=>click('Remember me'));await snap('remember-on');await action('Remember me off',()=>click('Remember me'));await action('Forgot password',()=>click('Forgot Password?'));await action('Google',()=>click('Google'));await action('Facebook',()=>click('Facebook'));await action('Email tab',()=>click('Email'));
 }
 await snap('login');await measure('login');const submit=actor==='customer'?'Login':actor==='plumber'?'Continue':actor==='store'?'Log In':'Sign in';
 await action('Email missing',async()=>{await p.locator('input[type=email]').fill('');await p.locator('input[type=password]').fill('');await click(submit)});
 await action('Malformed email submit',async()=>{await p.locator('input[type=email]').fill('not-an-email');await p.locator('input[type=password]').fill('qa-invalid-input');await click(submit)});await snap('invalid-email');await p.locator('input[type=email]').fill('');await p.locator('input[type=password]').fill('');
 if(actor==='customer'){await action('Google sign in',()=>click('Continue with Google'));await action('Create account',()=>click('Create Account'));await snap('registration');await measure('registration');}
 if(actor==='store'){await action('Remember me on',()=>click('Remember me'));await snap('remember-on');await action('Remember me off',()=>click('Remember me'));await action('Forgot password',()=>click('Forgot Password?'));await action('Register Store',()=>click('Register Store'));await snap('registration');await measure('registration');await action('Empty registration',()=>click('Create Store Account'));await snap('registration-empty');await action('Back to login',()=>click('Already registered? Log in'));}
 if(actor==='plumber'){await action('Mobile tab return',()=>click('Mobile'));await action('Registration entry',()=>p.getByText(/New here\? Sign up/).click());await snap('signup-result');if((await p.locator('body').innerText()).includes('Confirm password'))await measure('registration');}
 if(actor==='customer'){const text=await p.locator('body').innerText();console.log('CUSTOMER REG',text);const submitReg=p.getByRole('button',{name:/Create Account|Sign up|Register/i});if(await submitReg.count())await action('Empty registration',()=>submitReg.last().click());await snap('registration-empty');}
 await action('Refresh',()=>p.reload({waitUntil:'domcontentloaded'}));await p.locator('input,button').first().waitFor({timeout:30000});await snap('refreshed');
 const route=actor==='admin'?'/dashboard':actor==='customer'?'/orders':actor==='plumber'?'/jobs':'/inventory';await action('Unauthenticated deep link '+route,()=>p.goto(url+route,{waitUntil:'domcontentloaded',timeout:45000}));await snap('deep-link');await action('Browser back',()=>p.goBack({waitUntil:'domcontentloaded'}));await action('Browser forward',()=>p.goForward({waitUntil:'domcontentloaded'}));await snap('forward');
 }catch(e){save(actor+'-error.json',{error:e.message});console.log(actor,e.message)}finally{save(actor+'-events.json',events);save(actor+'-actions.json',actions);await c.close()}
}}finally{await b.close()}console.log('EVIDENCE',out)})().catch(e=>{console.error(e.message);process.exitCode=1});
