package com.pqc.core.controller;
import com.pqc.core.dto.*; import com.pqc.core.entity.*; import com.pqc.core.security.CurrentUser; import com.pqc.core.service.PlumberManagerService; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.Page; import org.springframework.web.bind.annotation.*; import java.util.List;
@RestController @RequestMapping("/api/v1/admin/plumber-manager") @RequiredArgsConstructor
public class PlumberManagerController {
 private final PlumberManagerService service; private final CurrentUser currentUser;
 @GetMapping("/dashboard") public PlumberManagerDashboardResponse dashboard(){return service.getDashboard();}
 @GetMapping("/plumbers") public Page<PlumberSummaryResponse> plumbers(@RequestParam(required=false) PlumberAvailabilityStatus status,@RequestParam(required=false) PlumberKycStatus kycStatus,@RequestParam(required=false) String search,@RequestParam(required=false) Double minRating,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){return service.listPlumbers(status,kycStatus,search,minRating,page,size);}
 @GetMapping("/plumbers/{id}") public PlumberDetailResponse plumber(@PathVariable Long id){return service.getPlumber(id);} @GetMapping("/kyc/pending") public List<PlumberKycSummaryResponse> pending(){return service.pendingKyc();} @GetMapping("/kyc/{id}") public PlumberKycDetailResponse kyc(@PathVariable Long id){return service.getKyc(id);}
 @PatchMapping("/kyc/{id}/approve") public PlumberKycSummaryResponse approve(@PathVariable Long id,@RequestBody(required=false) PlumberKycActionRequest request){return service.approveKyc(id,currentUser.require().getId(),request);} @PatchMapping("/kyc/{id}/reject") public PlumberKycSummaryResponse reject(@PathVariable Long id,@RequestBody PlumberKycActionRequest request){return service.rejectKyc(id,currentUser.require().getId(),request);}
 @GetMapping("/plumbers/{id}/jobs") public Page<PlumberJobSummaryResponse> jobs(@PathVariable Long id,@RequestParam(required=false) OrderStatus status,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){return service.getJobs(id,status,page,size);} @GetMapping("/plumbers/{id}/performance") public PlumberPerformanceResponse performance(@PathVariable Long id){return service.getPerformance(id);} @PatchMapping("/plumbers/{id}/availability") public PlumberSummaryResponse availability(@PathVariable Long id,@RequestBody PlumberAvailabilityUpdateRequest request){return service.updateAvailability(id,request);}
}
