package com.pqc.core.service;
import com.pqc.core.dto.*; import com.pqc.core.entity.*; import com.pqc.core.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.math.*; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class MarketingAdminService {
 private final OfferRepository offers; private final MarketingCampaignRepository campaigns; private final MarketingBannerRepository banners; private final MarketingNotificationRepository notifications; private final UserRepository users;
 public MarketingDashboardResponse dashboard(){LocalDateTime now=LocalDateTime.now();List<Offer> os=offers.findAll();List<MarketingCampaign> cs=campaigns.findAll();long usage=os.stream().mapToLong(Offer::getUsedCount).sum();return new MarketingDashboardResponse(os.stream().filter(o->o.isActive()&&!o.getStartsAt().isAfter(now)&&o.getEndsAt().isAfter(now)).count(),os.stream().filter(o->o.isActive()&&o.getStartsAt().isAfter(now)).count(),os.stream().filter(o->o.getEndsAt().isBefore(now)).count(),cs.stream().filter(c->c.getStatus()==CampaignStatus.ACTIVE).count(),cs.stream().filter(c->c.getStatus()==CampaignStatus.PAUSED).count(),banners.findAll().stream().filter(MarketingBanner::isActive).count(),notifications.findAll().stream().filter(n->n.getStatus()==MarketingNotificationStatus.SENT).count(),usage,discount(os),users.findAll().stream().filter(u->u.getCreatedAt()!=null&&YearMonth.from(u.getCreatedAt()).equals(YearMonth.now())).count(),0);}
 public Page<OfferSummaryResponse> listOffers(Boolean active,DiscountType type,String search,int page,int size){Specification<Offer>s=(r,q,cb)->{var p=cb.conjunction();if(active!=null)p=cb.and(p,cb.equal(r.get("active"),active));if(type!=null)p=cb.and(p,cb.equal(r.get("discountType"),type));if(search!=null&&!search.isBlank()){String x="%"+search.toLowerCase()+"%";p=cb.and(p,cb.or(cb.like(cb.lower(r.get("code")),x),cb.like(cb.lower(r.get("title")),x)));}return p;};return offers.findAll(s,page(page,size)).map(this::offerSummary);}
 @Transactional public OfferDetailResponse createOffer(OfferCreateRequest r){if(r==null||r.code()==null||r.code().isBlank()||offers.existsByCodeIgnoreCase(r.code().trim()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Offer code already exists");validateOffer(r.discountValue(),r.startsAt(),r.endsAt());Offer o=Offer.builder().code(r.code().trim().toUpperCase()).title(required(r.title(),"title")).description(r.description()).discountType(r.discountType()).discountValue(r.discountValue()).minOrderAmount(safe(r.minOrderAmount())).maxDiscountAmount(r.maxDiscountAmount()).usageLimit(r.usageLimit()).targetRole(r.targetRole()).startsAt(r.startsAt()).endsAt(r.endsAt()).active(true).build();return offerDetail(offers.save(o));}
 public OfferDetailResponse getOffer(Long id){return offerDetail(offer(id));}
 @Transactional public OfferDetailResponse updateOffer(Long id,OfferUpdateRequest r){Offer o=offer(id);validateOffer(r.discountValue(),r.startsAt(),r.endsAt());o.setTitle(required(r.title(),"title"));o.setDescription(r.description());o.setDiscountType(r.discountType());o.setDiscountValue(r.discountValue());o.setMinOrderAmount(safe(r.minOrderAmount()));o.setMaxDiscountAmount(r.maxDiscountAmount());o.setUsageLimit(r.usageLimit());o.setTargetRole(r.targetRole());o.setStartsAt(r.startsAt());o.setEndsAt(r.endsAt());return offerDetail(offers.save(o));}
 @Transactional public OfferDetailResponse setOfferActive(Long id,boolean active){Offer o=offer(id);o.setActive(active);return offerDetail(offers.save(o));}
 public Page<CampaignSummaryResponse> listCampaigns(CampaignStatus status,CampaignType type,String search,int page,int size){Specification<MarketingCampaign>s=(r,q,cb)->{var p=cb.conjunction();if(status!=null)p=cb.and(p,cb.equal(r.get("status"),status));if(type!=null)p=cb.and(p,cb.equal(r.get("campaignType"),type));if(search!=null&&!search.isBlank())p=cb.and(p,cb.like(cb.lower(r.get("name")),"%"+search.toLowerCase()+"%"));return p;};return campaigns.findAll(s,page(page,size)).map(this::campaignSummary);}
 @Transactional public CampaignDetailResponse createCampaign(CampaignCreateRequest r){validateDates(r.startsAt(),r.endsAt());MarketingCampaign c=MarketingCampaign.builder().name(required(r.name(),"name")).description(r.description()).campaignType(r.campaignType()).targetSegment(required(r.targetSegment(),"targetSegment")).status(r.status()==null?CampaignStatus.DRAFT:r.status()).startsAt(r.startsAt()).endsAt(r.endsAt()).build();return campaignDetail(campaigns.save(c));}
 public CampaignDetailResponse getCampaign(Long id){return campaignDetail(campaign(id));}
 @Transactional public CampaignDetailResponse updateCampaignStatus(Long id,CampaignStatusUpdateRequest r){MarketingCampaign c=campaign(id);CampaignStatus n=r==null?null:r.status();boolean valid=(c.getStatus()==CampaignStatus.DRAFT&&(n==CampaignStatus.SCHEDULED||n==CampaignStatus.ACTIVE))||(c.getStatus()==CampaignStatus.ACTIVE&&(n==CampaignStatus.PAUSED||n==CampaignStatus.COMPLETED))||(c.getStatus()==CampaignStatus.PAUSED&&(n==CampaignStatus.ACTIVE||n==CampaignStatus.CANCELLED));if(!valid)throw new ResponseStatusException(HttpStatus.CONFLICT,"Invalid campaign status transition");c.setStatus(n);return campaignDetail(campaigns.save(c));}
 public List<BannerSummaryResponse> listBanners(){return banners.findAll().stream().map(this::banner).toList();}
 @Transactional public BannerSummaryResponse createBanner(BannerCreateRequest r){validateDates(r.startsAt(),r.endsAt());return banner(banners.save(MarketingBanner.builder().title(required(r.title(),"title")).subtitle(r.subtitle()).imageUrl(r.imageUrl()).deeplink(r.deeplink()).placement(r.placement()).active(r.active()==null||r.active()).startsAt(r.startsAt()).endsAt(r.endsAt()).build()));}
 @Transactional public BannerSummaryResponse updateBanner(Long id,BannerUpdateRequest r){MarketingBanner b=bannerEntity(id);validateDates(r.startsAt(),r.endsAt());b.setTitle(required(r.title(),"title"));b.setSubtitle(r.subtitle());b.setImageUrl(r.imageUrl());b.setDeeplink(r.deeplink());b.setPlacement(r.placement());b.setStartsAt(r.startsAt());b.setEndsAt(r.endsAt());return banner(banners.save(b));}
 @Transactional public BannerSummaryResponse setBannerActive(Long id,boolean active){MarketingBanner b=bannerEntity(id);b.setActive(active);return banner(banners.save(b));}
 public List<MarketingNotificationResponse> listNotifications(){return notifications.findAllByOrderByCreatedAtDesc().stream().map(this::notification).toList();}
 @Transactional public MarketingNotificationResponse sendNotification(MarketingNotificationRequest r,Long adminId){MarketingNotification n=MarketingNotification.builder().title(required(r.title(),"title")).message(required(r.message(),"message")).targetSegment(required(r.targetSegment(),"targetSegment")).sentByAdminId(adminId).status(MarketingNotificationStatus.SENT).sentAt(LocalDateTime.now()).build();return notification(notifications.save(n));}
 public List<UserSegmentResponse> segments(){long all=users.count(),customers=users.countByRole(Role.CUSTOMER),plumbers=users.countByRole(Role.PLUMBER),stores=users.countByRole(Role.STORE_MANAGER),delivery=users.countByRole(Role.DELIVERY_PARTNER),newCustomers=users.findAll().stream().filter(u->u.getRole()==Role.CUSTOMER&&u.getCreatedAt()!=null&&u.getCreatedAt().isAfter(LocalDateTime.now().minusDays(30))).count();return List.of(new UserSegmentResponse("ALL_USERS","Every registered user",all),new UserSegmentResponse("CUSTOMERS","All customer accounts",customers),new UserSegmentResponse("PLUMBERS","All plumbers",plumbers),new UserSegmentResponse("STORE_MANAGERS","Store manager accounts",stores),new UserSegmentResponse("DELIVERY_PARTNERS","Delivery partners",delivery),new UserSegmentResponse("NEW_CUSTOMERS","Customers joined in 30 days",newCustomers),new UserSegmentResponse("ACTIVE_CUSTOMERS","Estimated active customers",customers),new UserSegmentResponse("INACTIVE_CUSTOMERS","No activity attribution available",0),new UserSegmentResponse("HIGH_VALUE_CUSTOMERS","No spend segmentation available",0));}
 public MarketingReportResponse report(){List<Offer> os=offers.findAll();List<MarketingCampaign> cs=campaigns.findAll();return new MarketingReportResponse(os.size(),os.stream().filter(Offer::isActive).count(),cs.size(),cs.stream().filter(c->c.getStatus()==CampaignStatus.ACTIVE).count(),notifications.findAll().stream().filter(n->n.getStatus()==MarketingNotificationStatus.SENT).count(),os.stream().mapToLong(Offer::getUsedCount).sum(),discount(os),LocalDateTime.now());}
 private Pageable page(int p,int s){return PageRequest.of(Math.max(0,p),Math.min(100,Math.max(1,s)),Sort.by("id").descending());} private Offer offer(Long id){return offers.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Offer not found"));} private MarketingCampaign campaign(Long id){return campaigns.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Campaign not found"));} private MarketingBanner bannerEntity(Long id){return banners.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Banner not found"));}
 private void validateOffer(BigDecimal value,LocalDateTime start,LocalDateTime end){if(value==null||value.signum()<=0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"discountValue must be positive");validateDates(start,end);} private void validateDates(LocalDateTime start,LocalDateTime end){if(start!=null&&end!=null&&!end.isAfter(start))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"end date must be after start date");} private String required(String v,String name){if(v==null||v.isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,name+" is required");return v.trim();} private BigDecimal safe(BigDecimal v){return v==null?BigDecimal.ZERO:v;} private BigDecimal discount(List<Offer> os){return os.stream().map(o->o.getDiscountValue().multiply(BigDecimal.valueOf(o.getUsedCount()))).reduce(BigDecimal.ZERO,BigDecimal::add);}
 private OfferSummaryResponse offerSummary(Offer o){return new OfferSummaryResponse(o.getId(),o.getCode(),o.getTitle(),o.getDiscountType(),o.getDiscountValue(),o.getMinOrderAmount(),o.getUsageLimit(),o.getUsedCount(),o.isActive(),o.getStartsAt(),o.getEndsAt());} private OfferDetailResponse offerDetail(Offer o){return new OfferDetailResponse(o.getId(),o.getCode(),o.getTitle(),o.getDescription(),o.getDiscountType(),o.getDiscountValue(),o.getMinOrderAmount(),o.getMaxDiscountAmount(),o.getUsageLimit(),o.getUsedCount(),o.getTargetRole(),o.isActive(),o.getStartsAt(),o.getEndsAt(),o.getCreatedAt(),o.getUpdatedAt());} private CampaignSummaryResponse campaignSummary(MarketingCampaign c){return new CampaignSummaryResponse(c.getId(),c.getName(),c.getCampaignType(),c.getTargetSegment(),c.getStatus(),c.getStartsAt(),c.getEndsAt());} private CampaignDetailResponse campaignDetail(MarketingCampaign c){return new CampaignDetailResponse(c.getId(),c.getName(),c.getDescription(),c.getCampaignType(),c.getTargetSegment(),c.getStatus(),c.getStartsAt(),c.getEndsAt(),c.getCreatedAt(),c.getUpdatedAt());} private BannerSummaryResponse banner(MarketingBanner b){return new BannerSummaryResponse(b.getId(),b.getTitle(),b.getSubtitle(),b.getImageUrl(),b.getDeeplink(),b.getPlacement(),b.isActive(),b.getStartsAt(),b.getEndsAt());} private MarketingNotificationResponse notification(MarketingNotification n){return new MarketingNotificationResponse(n.getId(),n.getTitle(),n.getMessage(),n.getTargetSegment(),n.getSentByAdminId(),n.getStatus(),n.getCreatedAt(),n.getSentAt());}
}
