package com.pqc.core.service;

import com.pqc.core.dto.*;
import com.pqc.core.entity.*;
import com.pqc.core.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;

@Service @RequiredArgsConstructor
public class PlumberManagerService {
    private static final List<OrderStatus> ACTIVE=List.of(OrderStatus.ACCEPTED,OrderStatus.IN_PROGRESS,OrderStatus.COMBINED_ORDER), DONE=List.of(OrderStatus.COMPLETED,OrderStatus.PAID);
    private final UserRepository userRepository; private final PlumberKycRepository plumberKycRepository; private final ServiceOrderRepository serviceOrderRepository; private final SettlementRepository settlementRepository;
    public PlumberManagerDashboardResponse getDashboard(){List<ServiceOrder> jobs=serviceOrderRepository.findAll();LocalDate today=LocalDate.now();return new PlumberManagerDashboardResponse(userRepository.countByRole(Role.PLUMBER),countAvailability(PlumberAvailabilityStatus.ONLINE),countAvailability(PlumberAvailabilityStatus.BUSY),offlineCount(),countAvailability(PlumberAvailabilityStatus.SUSPENDED),plumberKycRepository.countByStatus(PlumberKycStatus.PENDING),plumberKycRepository.countByStatus(PlumberKycStatus.APPROVED),plumberKycRepository.countByStatus(PlumberKycStatus.REJECTED),jobs.stream().filter(j->ACTIVE.contains(j.getStatus())).count(),jobs.stream().filter(j->DONE.contains(j.getStatus())&&j.getCompletedAt()!=null&&j.getCompletedAt().toLocalDate().equals(today)).count(),null,monthlyEarnings(jobs));}
    public Page<PlumberSummaryResponse> listPlumbers(PlumberAvailabilityStatus status,PlumberKycStatus kycStatus,String search,Double minRating,int page,int size){Specification<User> spec=(root,q,cb)->{var p=cb.equal(root.get("role"),Role.PLUMBER);if(search!=null&&!search.isBlank()){String s="%"+search.trim().toLowerCase()+"%";p=cb.and(p,cb.or(cb.like(cb.lower(root.get("fullName")),s),cb.like(cb.lower(root.get("email")),s),cb.like(root.get("phone"),s)));}return p;};Page<User> plumbers=userRepository.findAll(spec,PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by("id").descending()));List<PlumberSummaryResponse> filtered=plumbers.stream().map(this::summary).filter(p->status==null||p.availabilityStatus()==status).filter(p->kycStatus==null||p.kycStatus()==kycStatus).filter(p->minRating==null||p.rating()!=null&&p.rating()>=minRating).toList();return new PageImpl<>(filtered,plumbers.getPageable(),plumbers.getTotalElements());}
    public PlumberDetailResponse getPlumber(Long id){User p=plumber(id);List<ServiceOrder> jobs=jobs(id);PlumberPerformanceResponse perf=performance(jobs);PlumberKyc k=kyc(id);return new PlumberDetailResponse(p.getId(),p.getFullName(),p.getPhone(),p.getEmail(),p.getCreatedAt(),kycStatus(k),availability(k),jobs.size(),perf.activeJobs(),perf.completedJobs(),null,perf.totalEarnings(),perf.monthlyEarnings(),jobs.stream().sorted(Comparator.comparing(ServiceOrder::getId).reversed()).limit(10).map(this::job).toList(),List.of());}
    public List<PlumberKycSummaryResponse> pendingKyc(){return plumberKycRepository.findByStatusOrderBySubmittedAtAsc(PlumberKycStatus.PENDING).stream().map(this::kycSummary).toList();}
    public PlumberKycDetailResponse getKyc(Long id){return kycDetail(plumberKycRepository.findById(id).orElseThrow(()->notFound("KYC application")));}
    @Transactional public PlumberKycSummaryResponse approveKyc(Long id,Long adminId,PlumberKycActionRequest request){PlumberKyc k=pending(id);k.setStatus(PlumberKycStatus.APPROVED);k.setDocumentStatus(request!=null&&request.note()!=null?request.note():"VERIFIED");review(k,adminId);return kycSummary(plumberKycRepository.save(k));}
    @Transactional public PlumberKycSummaryResponse rejectKyc(Long id,Long adminId,PlumberKycActionRequest request){PlumberKyc k=pending(id);if(request==null||request.reason()==null||request.reason().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"reason is required");k.setStatus(PlumberKycStatus.REJECTED);k.setRejectionReason(request.reason().trim());review(k,adminId);return kycSummary(plumberKycRepository.save(k));}
    public Page<PlumberJobSummaryResponse> getJobs(Long id,OrderStatus status,int page,int size){plumber(id);Specification<ServiceOrder> spec=(root,q,cb)->{var p=cb.equal(root.get("plumber").get("id"),id);return status==null?p:cb.and(p,cb.equal(root.get("status"),status));};return serviceOrderRepository.findAll(spec,PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by("id").descending())).map(this::job);}
    public PlumberPerformanceResponse getPerformance(Long id){plumber(id);return performance(jobs(id));}
    @Transactional public PlumberSummaryResponse updateAvailability(Long id,PlumberAvailabilityUpdateRequest request){User p=plumber(id);if(request==null||request.status()==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"status is required");if(request.status()==PlumberAvailabilityStatus.SUSPENDED&&jobs(id).stream().anyMatch(j->ACTIVE.contains(j.getStatus())))throw new ResponseStatusException(HttpStatus.CONFLICT,"Cannot suspend a plumber with an active job");PlumberKyc k=plumberKycRepository.findByPlumberId(id).orElseGet(()->PlumberKyc.builder().plumberId(id).status(PlumberKycStatus.NOT_SUBMITTED).build());k.setAvailabilityStatus(request.status());k.setAvailabilityReason(request.reason());plumberKycRepository.save(k);return summary(p);}
    private PlumberPerformanceResponse performance(List<ServiceOrder> jobs){long completed=jobs.stream().filter(j->DONE.contains(j.getStatus())).count(),cancelled=jobs.stream().filter(j->j.getStatus()==OrderStatus.CANCELLED).count(),active=jobs.stream().filter(j->ACTIVE.contains(j.getStatus())).count();return new PlumberPerformanceResponse(completed,cancelled,active,null,null,earnings(jobs),earnings(jobs.stream().filter(j->j.getCompletedAt()!=null&&YearMonth.from(j.getCompletedAt()).equals(YearMonth.now())).toList()),null);}
    private PlumberSummaryResponse summary(User p){List<ServiceOrder> jobs=jobs(p.getId());PlumberKyc k=kyc(p.getId());return new PlumberSummaryResponse(p.getId(),p.getFullName(),p.getPhone(),p.getEmail(),availability(k),kycStatus(k),null,jobs.stream().filter(j->DONE.contains(j.getStatus())).count(),jobs.stream().filter(j->ACTIVE.contains(j.getStatus())).count(),earnings(jobs),p.getCreatedAt());}
    private PlumberJobSummaryResponse job(ServiceOrder j){return new PlumberJobSummaryResponse(j.getId(),j.getCustomer()==null?"UNKNOWN":j.getCustomer().getFullName(),j.getRequestType()==null?"UNKNOWN":j.getRequestType().name(),j.getStatus(),j.getTotalAmount(),j.getCreatedAt(),j.getCompletedAt());}
    private PlumberKycSummaryResponse kycSummary(PlumberKyc k){User p=userRepository.findById(k.getPlumberId()).orElse(null);return new PlumberKycSummaryResponse(k.getId(),k.getPlumberId(),p==null?"UNKNOWN":p.getFullName(),p==null?null:p.getPhone(),k.getExperienceYears(),k.getServiceAreas(),k.getSubmittedAt(),k.getStatus());}
    private PlumberKycDetailResponse kycDetail(PlumberKyc k){User p=userRepository.findById(k.getPlumberId()).orElse(null);return new PlumberKycDetailResponse(k.getId(),k.getPlumberId(),p==null?"UNKNOWN":p.getFullName(),p==null?null:p.getPhone(),p==null?null:p.getEmail(),k.getAadhaarNumberMasked(),k.getPanNumberMasked(),k.getBankAccountMasked(),k.getExperienceYears(),k.getServiceAreas(),k.getDocumentStatus(),k.getStatus(),k.getSubmittedAt(),k.getReviewedAt(),k.getReviewedByAdminId(),k.getRejectionReason());}
    private User plumber(Long id){User u=userRepository.findById(id).orElseThrow(()->notFound("Plumber"));if(u.getRole()!=Role.PLUMBER)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"User is not a plumber");return u;}
    private PlumberKyc pending(Long id){PlumberKyc k=plumberKycRepository.findById(id).orElseThrow(()->notFound("KYC application"));if(k.getStatus()!=PlumberKycStatus.PENDING)throw new ResponseStatusException(HttpStatus.CONFLICT,"Only pending KYC can be reviewed");return k;}
    private void review(PlumberKyc k,Long adminId){k.setReviewedByAdminId(adminId);k.setReviewedAt(LocalDateTime.now());} private List<ServiceOrder> jobs(Long id){return serviceOrderRepository.findByPlumber_Id(id);} private PlumberKyc kyc(Long id){return plumberKycRepository.findByPlumberId(id).orElse(null);} private PlumberKycStatus kycStatus(PlumberKyc k){return k==null?PlumberKycStatus.NOT_SUBMITTED:k.getStatus();} private PlumberAvailabilityStatus availability(PlumberKyc k){return k==null||k.getAvailabilityStatus()==null?PlumberAvailabilityStatus.OFFLINE:k.getAvailabilityStatus();} private long countAvailability(PlumberAvailabilityStatus s){return plumberKycRepository.countByAvailabilityStatus(s);} private long offlineCount(){return Math.max(0,userRepository.countByRole(Role.PLUMBER)-countAvailability(PlumberAvailabilityStatus.ONLINE)-countAvailability(PlumberAvailabilityStatus.BUSY)-countAvailability(PlumberAvailabilityStatus.SUSPENDED));} private BigDecimal earnings(List<ServiceOrder> jobs){return jobs.stream().filter(j->DONE.contains(j.getStatus())).map(ServiceOrder::getTotalAmount).filter(Objects::nonNull).reduce(BigDecimal.ZERO,BigDecimal::add);} private BigDecimal monthlyEarnings(List<ServiceOrder> jobs){return earnings(jobs.stream().filter(j->j.getPlumber()!=null&&j.getCompletedAt()!=null&&YearMonth.from(j.getCompletedAt()).equals(YearMonth.now())).toList());} private ResponseStatusException notFound(String thing){return new ResponseStatusException(HttpStatus.NOT_FOUND,thing+" not found");}
}
