package com.pqc.core.security;

import com.pqc.core.entity.*; import com.pqc.core.repository.*;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import java.time.LocalDateTime;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class PlumberManagerControllerTest {
 @Autowired MockMvc mvc; @Autowired UserRepository users; @Autowired PlumberKycRepository kycs; @Autowired PasswordEncoder encoder; @Autowired JwtService jwt; @Autowired JdbcTemplate jdbc; private User manager,plumber,customer; private PlumberKyc kyc;
 @BeforeEach void setup(){jdbc.execute("SET REFERENTIAL_INTEGRITY FALSE");for(String table:new String[]{"plumber_kyc","support_messages","support_tickets","refund_requests","settlements","outbox_events","inventory_reservations","product_order_items","product_orders","service_orders","stocks","stores","user_addresses","wallet_transactions","wallets","refresh_tokens","notifications","users"})try{jdbc.execute("TRUNCATE TABLE "+table+" RESTART IDENTITY");}catch(Exception ignored){}jdbc.execute("SET REFERENTIAL_INTEGRITY TRUE");manager=save("manager@pm.test",Role.PLUMBER_MANAGER);plumber=save("plumber@pm.test",Role.PLUMBER);customer=save("customer@pm.test",Role.CUSTOMER);kyc=kycs.save(PlumberKyc.builder().plumberId(plumber.getId()).aadhaarNumberMasked("XXXX-XXXX-1234").panNumberMasked("ABCDE****F").bankAccountMasked("XXXX4321").experienceYears(5).serviceAreas("Central, North").status(PlumberKycStatus.PENDING).submittedAt(LocalDateTime.now()).build());}
 @Test void managerCanListAndViewPlumber(){try{mvc.perform(get("/api/v1/admin/plumber-manager/plumbers").header("Authorization",bearer(manager))).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].plumberId").value(plumber.getId()));mvc.perform(get("/api/v1/admin/plumber-manager/plumbers/{id}",plumber.getId()).header("Authorization",bearer(manager))).andExpect(status().isOk()).andExpect(jsonPath("$.fullName").value(plumber.getFullName()));}catch(Exception e){throw new RuntimeException(e);}}
 @Test void managerCanApprovePendingKyc() throws Exception {mvc.perform(patch("/api/v1/admin/plumber-manager/kyc/{id}/approve",kyc.getId()).header("Authorization",bearer(manager)).contentType(MediaType.APPLICATION_JSON).content("{\"note\":\"Documents verified\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("APPROVED"));}
 @Test void managerCanRejectPendingKyc() throws Exception {mvc.perform(patch("/api/v1/admin/plumber-manager/kyc/{id}/reject",kyc.getId()).header("Authorization",bearer(manager)).contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"PAN unclear\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("REJECTED"));}
 @Test void rejectsMissingReasonAndNonPlumberAvailability() throws Exception {mvc.perform(patch("/api/v1/admin/plumber-manager/kyc/{id}/reject",kyc.getId()).header("Authorization",bearer(manager)).contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"\"}")).andExpect(status().isBadRequest());mvc.perform(patch("/api/v1/admin/plumber-manager/plumbers/{id}/availability",customer.getId()).header("Authorization",bearer(manager)).contentType(MediaType.APPLICATION_JSON).content("{\"status\":\"OFFLINE\"}")).andExpect(status().isBadRequest());}
 private User save(String email,Role role){return users.save(User.builder().email(email).password(encoder.encode("password")).fullName(role.name()+" User").phone("9"+Math.abs(email.hashCode())).role(role).status(UserStatus.ACTIVE).build());} private String bearer(User u){return "Bearer "+jwt.generateToken(u.getEmail(),u.getRole().name());}
}
